# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Recipe.create([
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
    {title: "Creamy Shrimp Scampi with Half-and-Half", image: "https://images.media-allrecipes.com/userphotos/560x315/5860407.jpg", ingredients: ["1/2 (16 ounce) package linguine pasta", "4 tablespoons butter", "2 cloves garlic, minced", "1 pound jumbo shrimp, peeled and deveined", "2 tablespoons Pinot Grigio wine", "2 teaspoons lemon juice, or to taste", "1/2 cup half-and-half"], instructions: "Bring a large pot of lightly salted water to a boil. Cook linguine at a boil until tender yet firm to the bite, about 8 minutes. While pasta cooks, melt 2 tablespoons butter in a skillet over medium heat. Add garlic and cook until fragrant and lightly browned, about 1 minute. Add shrimp and cook until tails start curling in, about 2 minutes per side. Add remaining butter, Pinot Grigio, lemon juice, half-and-half, and Parmesan cheese. Stir to incorporate. Drain linguine and divide noodles between 2 bowls. Serve shrimp mixture on top and garnish with parsley."},
])