# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Recipe.create([
    {title: "Delicious", difficulty: "Easy", image: "https://s23209.pcdn.co/wp-content/uploads/2015/04/IMG_5101edit-1.jpg", ingredients: ["1 1/2 cups brown rice", "Fat (meat or oil)", "1 tablespoon olive oil", "3 pounds ground turkey", "3 cups baby spinach, chopped", "2 carrots, shredded", "1 zucchini, shredded", "1/2 cup peas, canned or frozen"], instructions: "Now this recipe here has a balance of 50% protein, 25% veggies and 25% grains, but the ratios can easily be adjusted to suit your pup’s breed and/or needs. In a large saucepan of 3 cups water, cook rice according to package instructions; set aside. Heat olive oil in a large stockpot or Dutch oven over medium heat. Add ground turkey and cook until browned, about 3-5 minutes, making sure to crumble the turkey as it cooks. Stir in spinach, carrots, zucchini, peas and brown rice until the spinach has wilted and the mixture is heated through, about 3-5 minutes. Let cool completely."},
    {title: "The Mix & Match", difficulty: "Easy", image: "https://images.media-allrecipes.com/userphotos/720x405/1432665.jpg", ingredients: ["6 cups water", "1 pound ground turkey", "2 cloves garlic, minced", "2 cups brown rice", "1 teaspoon dried rosemary", "1/2 (16 ounce) package frozen broccoli, carrots and cauliflower combination", "1/2 cup half-and-half"], instructions: "Place the water, ground turkey, rice, and rosemary into a large Dutch oven. Stir until the ground turkey is broken up and evenly distributed throughout the mixture; bring to a boil over high heat, then reduce heat to low and simmer for 20 minutes. Add the frozen vegetables, and cook for an additional 5 minutes. Remove from heat and cool. Refrigerate until using."},
    {title: "The Perfect Treat", difficulty: "Hard", image: "https://www.momontimeout.com/wp-content/uploads/2019/09/homemade-dog-treats-recipe-with-title-733x1002.jpg", ingredients: ["1 cup pumpkin puree", "2 eggs", "1/3 cup peanut butter natural, NO Xylitol or sugar substitutes", "2 cups whole wheat flour all purpose can be used instead", "1/2 tsp pumpkin pie spice or cinnamon (check your pumpkin pie spice or make your own - NO nutmeg, can be toxic to some dogs)"], instructions: "Preheat oven to 350F. Line a large baking sheet with a silicone baking mat or parchment paper. In a large bowl, combine pumpkin, eggs, and peanut butter. Stir until completely combined. Add in flour and pumpkin pie spice (or cinnamon) - stirring just until combined. Lightly flour a flat surface and roll out dough to one quarter inch, using flour as needed to keep dough from sticking. Cut shapes out of dough and place on prepared baking sheet. Bake for 20 to 40 minutes - depending on desired level of crunchiness. Remove treats from oven and let cool on a cooling rack. Store in an airtight container for up to 1 month in the refrigerator or 6 months in the freezer."},
    {title: "Macarooni", difficulty: "Easy", image: "https://wheresthefrenchie.com/wp-content/uploads/2016/11/homemade-dog-food-storage-1024x698.jpg", ingredients: ["3 lbs ground turkey (or any protein)", "1 cup uncooked millet (or any other whole grain: quinoa, rice, pasta)", "1 tbs olive oil", "1 carrot, shredded", "1 zucchini, shredded", "1 squash, shredded", "1 apple, chopped", "1 tbs calcium powder", "1/4 cup unsweetened coconut flakes or coconut oil", "1/2 cup pumpkin puree (canned or homemade)"], instructions: "Bring 1 cup of whole grain to boil in a pot of water. I overcook it so that it’s soft and easily digestible. Drain. While that’s boiling, shred/chop the veggies. Cook ground turkey with olive oil and drain excess juices. Mix everything together! No need to cook the veggies. The cooked turkey and whole grain will warm them up a bit."},
    {title: "The Crock Pot", difficulty: "Easy", ingredients: ["2 1/2 pounds ground beef", "1 1/2 cups brown rice", "1 (15-ounce) can kidney beans, drained and rinsed", "1 1/2 cups chopped butternut squash", "1 1/2 cups chopped carrots", "1/2 cup peas, frozen or canned"], instructions: "Stir in ground beef, brown rice, kidney beans, butternut squash, carrots, peas and 4 cups water into a 6-qt slow cooker. Cover and cook on low heat for 5-6 hours or high heat for 2-3 hours, stirring as needed. Let cool completely."},
    {title: "CBD-Infused Dog Treats", difficulty: "Medium", image: "https://www.caninejournal.com/wp-content/uploads/cbd-dog-treat-jpg.jpg", ingredients: ["2 1/2 cups gluten-free flour", "1/2 cup oats", "1 cup pumpkin puree", "1 Tbsp coconut sugar, 1 apple, cored and grated", "1/2 cup carrots, peeled and grated", "1/2 cup peanut butter, 1 egg, beaten", "1/3 cup olive or coconut oil", "1/2 cup water", "dash of sea salt", "120 mg CBD oil"], instructions: "Total: Makes 24 treats. Preheat the oven to 350ºF. Grease a dog cookie baking tray with coconut oil. Core and grate the apples, then peel and grate the carrots. In a medium-sized bowl, combine the gluten-free flour, oats, and coconut sugar together. In another medium-sized bowl, beat the egg. Then, add coconut oil, water, and grated apples and carrots. Add wet ingredients to dry ingredients bowl; mix completely. Finally, add CBD oil and mix once more. Using a Tbsp measuring spoon, portion out the dog biscuits and press into the dog treat baking pan. Bake 32-37 minutes or until the biscuits are firm and golden-brown on the outside. Store in an air-tight container. The number of dog treats will vary depending on the size of the mold you use. Try to make each dog treat have 2-5 mg of CBD."},
    {title: "Beef Stew, Doggie Style", difficulty: "Easy", image: "https://www.caninejournal.com/wp-content/uploads/diced-carrots-and-knive.jpg", ingredients: ["1 pound of beef stew meat", "1 small sweet potato", "1/2 cup of carrots, diced", "1/2 cup of green beans, diced", "1/2 cup of flour", "1/2 cup of water", "1 tablespoon of vegetable oil"], instructions: "Cook the sweet potato in a microwave for 5 to 8 minutes until firm but tender. Set aside. Slice the beef into small chunks, about the size of a nickel. Cook the beef stew pieces in a tablespoon of vegetable oil over medium heat for 10-15 minutes or until well-done. Remove the beef chunks from the pan, reserving the drippings. Dice the sweet potato. Heat the drippings over medium-low heat. Slowly add flour and water into the drippings while whisking to create a thick gravy. Add the meat, sweet potato, carrots and green beans into the gravy and stir to coat. Cook until the carrots are tender — about 10 minutes. Let it cool and serve. Store remaining stew in the fridge for up to 5 days."},
    {title: "Grain-Free: Chicken Jerky Strips", difficulty: "Medium", ingredients: ["2 to 4 boneless, 3-oz skinless chicken breasts"], instructions: "Preheat oven to 200 degrees. Trim all excess fat off the chicken breasts. Cut into 1/8 inch thick strips using a paring knife. Bake for 2 hours on a baking sheet until the strips are dry and hard. Cool completely before presenting to your pooch."},
    {title: "Frozen Banana Treats", difficulty: "Easy", image: "https://www.caninejournal.com/wp-content/uploads/creamy-peanut-butter.jpg", ingredients: ["4 cups plain yogurt", "2 tablespoons peanut butter (make sure it’s xylitol free)", "3 ripe bananas, peeled & mashed"], instructions: "Blend all ingredients into a puree. Pour into 4-ounce plastic cups (ice trays or toddler popsicle trays work well). Freeze until firm. Can keep in the freezer for up to 2 weeks."},
    {title: "Turkey Burgers", difficulty: "Easy", image: "https://thebark.com/sites/default/files/styles/full/public/content/article/full/meatstuff.jpg?itok=9Fr1WA8V", ingredients: ["6 1/2 lbs. ground dark-meat turkey", "3 eggs", "3 tsp. ground dried eggshells", "3 tsp. chia", "1/2 c. garbanzo bean flour", "1/3 c. wheat bran", "2 Tbsp. ground flax seed", "1 c. plain organic pumpkin", "3 c. organic rolled oats", "2 Tbsp. rehydrated dried shredded seaweed (low-sodium variety)"], instructions: "Preheat oven to 400°. Mix well, making sure all the ingredients are completely incorporated. Shape into 3-inch patties, place on lightly oiled (with spray oil), rimmed baking sheet(s). Optional: Spread little ketchup (about 1/8 tsp.) on top of each patty. Bake 45 minutes to 1 hour. A longer baking time will produce a drier and easier-to-crumble burger. Tip: Deglaze the baking sheet with water, which makes a great gravy that can be used to moisten the meal. This recipe makes around 1 1/2 to 2 cups of this gravy. It’s also an easy way to help clean the baking pan."},
])